name: kapadokya_balon_app
description: Kapadokya balon kaptanları için bir Flutter tablet uygulaması.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Bileşenleri
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  lottie: ^3.3.1

  # State Yönetimi
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1

  # Navigasyon
  go_router: ^16.1.0

  # Network ve Veri
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Yardımcı Paketler
  intl: ^0.20.2
  logger: ^2.6.1
  internet_connection_checker: ^3.0.1

  # Sensör Göstergeleri (Balon uygulaması için)
  syncfusion_flutter_gauges: ^30.2.5
  syncfusion_flutter_charts: ^30.2.5
  equatable: ^2.0.7
  dartz: ^0.10.1

  # Firebase
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  # Ek olarak push notification için:
  firebase_messaging: ^16.0.0


  # Yerel Depolama ve Yüz Tanıma
  google_mlkit_face_detection: ^0.13.1
  image: ^4.3.0
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0
  path_provider: ^2.1.5

  # Alkolmetre modülü için gerekli bağımlılıklar
  google_mlkit_text_recognition: ^0.15.0
  camera: ^0.11.2
  ultralytics_yolo: ^0.1.34
  firebase_storage: ^13.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/mobile_face_net.tflite

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700