// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxDUJdoqK2FmXVdSMQAf0ifmQbEDULvYM',
    appId: '1:447462828242:web:07b7deafaea35565c8e50b',
    messagingSenderId: '447462828242',
    projectId: 'sky-vision-control-5ca1b',
    authDomain: 'sky-vision-control-5ca1b.firebaseapp.com',
    storageBucket: 'sky-vision-control-5ca1b.firebasestorage.app',
    measurementId: 'G-HKPJGFJTG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGsLqWgPUG28-ccun0R4sfkGlbXKZ4POs',
    appId: '1:447462828242:android:a576c34d7c725b08c8e50b',
    messagingSenderId: '447462828242',
    projectId: 'sky-vision-control-5ca1b',
    storageBucket: 'sky-vision-control-5ca1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV_zo-9agJJyRPOwY8xgbRrg0ERqqfKHI',
    appId: '1:447462828242:ios:f8b1f69b9d26cf87c8e50b',
    messagingSenderId: '447462828242',
    projectId: 'sky-vision-control-5ca1b',
    storageBucket: 'sky-vision-control-5ca1b.firebasestorage.app',
    iosBundleId: 'com.example.kapadokyaBalonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV_zo-9agJJyRPOwY8xgbRrg0ERqqfKHI',
    appId: '1:447462828242:ios:f8b1f69b9d26cf87c8e50b',
    messagingSenderId: '447462828242',
    projectId: 'sky-vision-control-5ca1b',
    storageBucket: 'sky-vision-control-5ca1b.firebasestorage.app',
    iosBundleId: 'com.example.kapadokyaBalonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxDUJdoqK2FmXVdSMQAf0ifmQbEDULvYM',
    appId: '1:447462828242:web:e315b3ce3c67c582c8e50b',
    messagingSenderId: '447462828242',
    projectId: 'sky-vision-control-5ca1b',
    authDomain: 'sky-vision-control-5ca1b.firebaseapp.com',
    storageBucket: 'sky-vision-control-5ca1b.firebasestorage.app',
    measurementId: 'G-G3C7FLFBV4',
  );

}